spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
#    sentinel:
#      transport:
#        dashboard: localhost:8080

server:
  port: 9090

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center # 多个以, 分割

feign:
  client:
    config:
      # 想要调用的微服务名称
      user-center:
        loggerLevel: FULL
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-group

logging:
  level:
    com.alibaba.nacos: error

jwt:
  secret: erudev
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
